name: petrovich
version: 0.1.0
author: Alexey Salnikov <me@iamsalnikov.ru>
homepage: https://github.com/iamsalnikov/petrovich-dart
description:
  A library to inflect Russian anthroponyms such as first names, last names, and middle names.
  Port of https://github.com/petrovich/petrovich-ruby
dependencies:
  unittest: "0.11.0+2"
